stages:
  - build
  - test
  - deploy

appimage-builder:
  stage: build
  image: 
    name: "carlonluca/qt-dev@sha256:1daabb99a1048556b11c0aebc3fe3695358c3ac53fd9a4c8dbefb6a7f285e919"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - appimage-builder --recipe ../AppImageBuilder.yml
  artifacts:
    paths:
      - build/PIP-OS-*.AppImage
