stages:
  - build
  - test
  - deploy

appimage-builder:
  stage: build
  image:
    name: "carlonluca/qt-dev:6.7.1"
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - mkdir build
    - cd build
  script:
    - appimage-builder --recipe ../AppImageBuilder.yml
  artifacts:
    paths:
      - build/PIP-OS-*.AppImage
